
symfonycasts_sass:
  root_sass:
    - '%kernel.project_dir%/assets/styles/style.scss'
    - '%kernel.project_dir%/assets/styles/style-dark.scss'
    - '%kernel.project_dir%/assets/styles/mail.scss'
    - '%kernel.project_dir%/assets/styles/error.scss'
