twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        fallbacks: "@framework.fallbacks"
        jsData: "@framework.jsdata"
        locales: "%locales%"
        theme: "@framework.theme"
        breadcrumbs: '@SumoCoders\FrameworkCoreBundle\Service\BreadcrumbTrail'
    form_themes:
        - "bootstrap_4_layout.html.twig"
        - "@SumoCodersFrameworkCore/Form/fields.html.twig"
        - "blocks.html.twig"
    paths:
        # We add our public folder to the default twig path so we can load the
        # mail stylesheet into the inline_css inside the base email template.
        "%kernel.project_dir%/public/": ~