twig:
    globals:
        fallbacks: "@framework.fallbacks"
        locales: "%locales%"
        breadcrumbs: '@SumoCoders\FrameworkCoreBundle\Service\BreadcrumbTrail'
        page_title: '@SumoCoders\FrameworkCoreBundle\Service\PageTitle'
    form_themes:
        - "bootstrap_5_layout.html.twig"
        - "@SumoCodersFrameworkCore/Form/fields.html.twig"
        - "blocks.html.twig"

    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
