framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async: 'in-memory://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
